### ISSUE TITLE
triggers-nivel-baixo

### ISSUE THREAD

**Issue by AugustoTSantos** [GroupHextech/HEXTECH-API5sem#39]
Criar triggers.sql junto com os outros arquivos .sql e fazer triggers que vão acionar quando o nível do estoque ficar igual ao valor de estoque mínimo.
A trigger deve mostrar o nome do produto, e uma mensagem indicando o valor do estoque atual

**Comment by williamantoniazzi** [comment]
Item criado em BD e atualizado em github em diretório scripts trigger.sql.
